2025-07-19 07:04:10,536: Watching for file changes with StatReloader
2025-07-19 07:04:25,517: Not Found: /favicon.ico
2025-07-19 07:04:39,322: Created 927 records
2025-07-19 07:04:39,706: Created 505 records
2025-07-19 07:04:39,847: Created 505 records
2025-07-19 07:04:39,847: updateData/shp/polymean.shp is Created
2025-07-19 07:04:40,312: Internal Server Error: /admin/updateData/propertymodel/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2057, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1686, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 607, in makeshape
    Insert()
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 604, in Insert
    lm.save(strict=True, verbose=verbose)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/utils/layermapping.py", line 728, in save
    _save()
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/utils/layermapping.py", line 664, in _save
    m.save(using=self.using)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1864, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.DataError: integer out of range

2025-07-19 07:04:51,236: /home/mohammad/w/AmlakNama/updateData/services.py changed, reloading.
2025-07-19 07:04:52,458: Watching for file changes with StatReloader
2025-07-19 07:05:01,895: Created 100 records
2025-07-19 07:05:02,034: Created 74 records
2025-07-19 07:05:02,066: Created 74 records
2025-07-19 07:05:02,066: updateData/shp/polymean.shp is Created
2025-07-19 07:05:02,122: Internal Server Error: /admin/updateData/propertymodel/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/gdal/datasource.py", line 67, in __init__
    ds = capi.open_ds(
         ^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/gdal/prototypes/errcheck.py", line 131, in check_pointer
    raise GDALException('Invalid pointer returned from "%s"' % func.__name__)
django.contrib.gis.gdal.error.GDALException: Invalid pointer returned from "GDALOpenEx"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2057, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1686, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 607, in makeshape
    Insert()
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 603, in Insert
    lm = LayerMapping(MTPPolygon,MTP_shp,MTP_mapping,transform=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/utils/layermapping.py", line 117, in __init__
    self.ds = DataSource(data, encoding=encoding)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/gdal/datasource.py", line 77, in __init__
    raise GDALException('Could not open the datasource at "%s"' % ds_input)
django.contrib.gis.gdal.error.GDALException: Could not open the datasource at "/home/mohammad/w/AmlakNama/updateData/updateData/shp/polymean.shp"
2025-07-19 07:05:43,683: /home/mohammad/w/AmlakNama/updateData/services.py changed, reloading.
2025-07-19 07:05:44,711: Watching for file changes with StatReloader
2025-07-19 07:05:51,502: Created 100 records
2025-07-19 07:05:51,611: Created 74 records
2025-07-19 07:05:51,630: Created 74 records
2025-07-19 07:05:51,630: updateData/shp/polymean.shp is Created
2025-07-19 07:05:51,767: Internal Server Error: /admin/updateData/propertymodel/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2057, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1686, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 607, in makeshape
    Insert()
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 604, in Insert
    lm.save(strict=True, verbose=verbose)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/utils/layermapping.py", line 728, in save
    _save()
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/utils/layermapping.py", line 664, in _save
    m.save(using=self.using)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1864, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.DataError: integer out of range

2025-07-19 07:10:03,443: /home/mohammad/w/AmlakNama/explore/models.py changed, reloading.
2025-07-19 07:10:04,507: Watching for file changes with StatReloader
2025-07-19 07:49:34,295: Watching for file changes with StatReloader
2025-07-19 07:49:54,858: Created 100 records
2025-07-19 07:49:55,023: Created 74 records
2025-07-19 07:49:55,055: Created 74 records
2025-07-19 07:49:55,056: updateData/shp/polymean.shp is Created
2025-07-19 07:50:15,021: Created 927 records
2025-07-19 07:50:15,916: Created 505 records
2025-07-19 07:50:16,022: Created 505 records
2025-07-19 07:50:16,023: updateData/shp/polymean.shp is Created
2025-07-19 08:38:16,536: Watching for file changes with StatReloader
2025-07-19 08:39:21,352: /home/mohammad/w/AmlakNama/explore/urls.py changed, reloading.
2025-07-19 08:39:22,714: Watching for file changes with StatReloader
2025-07-19 08:57:09,523: /home/mohammad/w/AmlakNama/explore/__init__.py changed, reloading.
2025-07-19 08:57:11,458: Watching for file changes with StatReloader
2025-07-19 10:16:03,823: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,823: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:03,824: GDAL_ERROR 1: b'Reprojection failed, err = 2049, further errors will be suppressed on the transform object.'
2025-07-19 10:16:03,824: Error transforming geometry from srid '4326' to srid '3857' (OGR failure.)
2025-07-19 10:16:49,268: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,268: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:16:49,269: GDAL_ERROR 1: b'Reprojection failed, err = 2049, further errors will be suppressed on the transform object.'
2025-07-19 10:16:49,269: Error transforming geometry from srid '4326' to srid '3857' (OGR failure.)
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,453: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'Reprojection failed, err = 2049, further errors will be suppressed on the transform object.'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,454: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,455: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,456: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:17:31,457: Error transforming geometry from srid '4326' to srid '3857' (OGR failure.)
2025-07-19 10:34:53,370: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,371: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'Reprojection failed, err = 2049, further errors will be suppressed on the transform object.'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,372: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,373: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,374: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,375: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,376: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:53,377: Error transforming geometry from srid '4326' to srid '3857' (OGR failure.)
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,906: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'Reprojection failed, err = 2049, further errors will be suppressed on the transform object.'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,907: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,908: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,909: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,910: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,911: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,912: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,912: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,912: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,912: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,912: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,912: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-19 10:34:58,912: Error transforming geometry from srid '4326' to srid '3857' (OGR failure.)
2025-07-20 09:10:49,778: Watching for file changes with StatReloader
2025-07-20 09:10:57,459: Not Found: /favicon.ico
2025-07-20 09:11:17,147: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,147: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,148: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'Reprojection failed, err = 2049, further errors will be suppressed on the transform object.'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,149: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,150: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,151: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,152: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,153: GDAL_ERROR 1: b'PROJ: webmerc: Invalid latitude'
2025-07-20 09:11:17,153: Error transforming geometry from srid '4326' to srid '3857' (OGR failure.)
2025-07-20 11:46:12,954: /home/mohammad/w/AmlakNama/updateData/services.py changed, reloading.
2025-07-20 11:46:14,210: Watching for file changes with StatReloader
2025-07-20 11:46:36,100: Created 927 records
2025-07-20 11:46:36,602: Created 505 records
2025-07-20 11:46:36,666: Created 505 records
2025-07-20 11:46:36,667: updateData/shp/polymean.shp is Created
2025-07-20 11:46:36,760: Internal Server Error: /admin/updateData/propertymodel/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2057, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1686, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 622, in makeshape
    insertshape(MTPPolygon,"polymean.shp","MULTIPOLYGON")
  File "/home/mohammad/w/AmlakNama/updateData/services.py", line 601, in insertshape
    lm = LayerMapping(model,shp_path,di,transform=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/utils/layermapping.py", line 132, in __init__
    self.check_layer()
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/contrib/gis/utils/layermapping.py", line 300, in check_layer
    raise LayerMapError(
django.contrib.gis.utils.layermapping.LayerMapError: OGR field "<class 'django.contrib.gis.gdal.field.OFTReal'>" (of type OFTReal) cannot be mapped to Django CharField.
2025-07-20 11:50:41,484: /home/mohammad/w/AmlakNama/updateData/services.py changed, reloading.
2025-07-20 11:50:42,406: Watching for file changes with StatReloader
2025-07-20 11:50:52,203: Created 927 records
2025-07-20 11:50:52,634: Created 505 records
2025-07-20 11:50:52,712: Created 505 records
2025-07-20 11:50:52,712: updateData/shp/polymean.shp is Created
2025-07-20 12:40:10,326: Not Found: /favicon.ico
2025-07-20 12:40:15,440: Not Found: /home/resland_{{ typ }}_{{ reg }}_{{ ActiveTile }}/
2025-07-20 12:42:45,953: /home/mohammad/w/AmlakNama/explore/urls.py changed, reloading.
2025-07-20 12:42:47,129: Watching for file changes with StatReloader
2025-07-20 12:47:39,031: /home/mohammad/w/AmlakNama/explore/urls.py changed, reloading.
2025-07-20 12:47:39,919: Watching for file changes with StatReloader
2025-07-20 12:49:10,338: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 12:49:11,260: Watching for file changes with StatReloader
2025-07-20 12:50:21,794: Not Found: /favicon.ico
2025-07-20 12:51:24,913: Not Found: /favicon.ico
2025-07-20 13:05:17,377: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:05:18,819: Watching for file changes with StatReloader
2025-07-20 13:05:23,709: Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/request.py", line 422, in __getattr__
    return getattr(_request, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'qury_params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/views.py", line 33, in get
    data = self.paramSerializer(data= request.qury_params)
                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/request.py", line 424, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{attr}'")
AttributeError: 'Request' object has no attribute 'qury_params'. Did you mean: 'query_params'?
2025-07-20 13:05:23,904: Not Found: /favicon.ico
2025-07-20 13:05:31,046: Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/request.py", line 422, in __getattr__
    return getattr(_request, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'qury_params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/views.py", line 33, in get
    data = self.paramSerializer(data= request.qury_params)
                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/request.py", line 424, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{attr}'")
AttributeError: 'Request' object has no attribute 'qury_params'. Did you mean: 'query_params'?
2025-07-20 13:05:38,285: Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/request.py", line 422, in __getattr__
    return getattr(_request, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'qury_params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/views.py", line 33, in get
    data = self.paramSerializer(data= request.qury_params)
                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/request.py", line 424, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{attr}'")
AttributeError: 'Request' object has no attribute 'qury_params'. Did you mean: 'query_params'?
2025-07-20 13:05:47,157: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:05:48,047: Watching for file changes with StatReloader
2025-07-20 13:05:49,437: Bad Request: /index/
2025-07-20 13:05:54,717: Bad Request: /index/
2025-07-20 13:06:40,735: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:06:41,693: Watching for file changes with StatReloader
2025-07-20 13:08:05,388: Watching for file changes with StatReloader
2025-07-20 13:08:09,045: Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/views.py", line 48, in get
    'RegionList' : dt['RegionList'],
                   ^^
UnboundLocalError: cannot access local variable 'dt' where it is not associated with a value
2025-07-20 13:09:02,915: Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/views.py", line 48, in get
    'RegionList' : dt['RegionList'],
                   ^^
UnboundLocalError: cannot access local variable 'dt' where it is not associated with a value
2025-07-20 13:09:42,505: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:09:43,527: Watching for file changes with StatReloader
2025-07-20 13:09:45,853: Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/views.py", line 35, in get
    dt = createmap(
         ^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/services.py", line 21, in createmap
    mp = Pgdf.query(f'landuse == "{lu}" and ptype == "{typ}"'+ txt)
                                                               ^^^
UnboundLocalError: cannot access local variable 'txt' where it is not associated with a value
2025-07-20 13:12:34,896: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:12:35,772: Watching for file changes with StatReloader
2025-07-20 13:12:38,685: Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/mohammad/w/AmlakNama/venv/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/views.py", line 35, in get
    dt = createmap(
         ^^^^^^^^^^
  File "/home/mohammad/w/AmlakNama/explore/services.py", line 30, in createmap
    popup=popupf,
          ^^^^^^
UnboundLocalError: cannot access local variable 'popupf' where it is not associated with a value
2025-07-20 13:14:48,388: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:14:49,259: Watching for file changes with StatReloader
2025-07-20 13:15:28,084: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:15:29,332: Watching for file changes with StatReloader
2025-07-20 13:18:03,557: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:18:04,781: Watching for file changes with StatReloader
2025-07-20 13:21:47,068: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:21:48,276: Watching for file changes with StatReloader
2025-07-20 13:26:08,322: /home/mohammad/w/AmlakNama/explore/services.py changed, reloading.
2025-07-20 13:26:09,563: Watching for file changes with StatReloader
2025-07-20 13:29:41,757: /home/mohammad/w/AmlakNama/explore/views.py changed, reloading.
2025-07-20 13:29:42,609: Watching for file changes with StatReloader
2025-07-20 13:31:53,478: update(res, buy) is run.
2025-07-20 13:31:53,479: update(res, rent) is run.
2025-07-20 13:31:53,479: update(resland, buy) is run.
2025-07-20 13:31:53,480: update(com, rent) is run.
2025-07-20 13:31:53,481: update(com, buy) is run.
2025-07-20 13:31:53,651: Pcases not found. status code: 200.
2025-07-20 13:31:53,799: [res- rent] - get 22 Pcasses
2025-07-20 13:31:53,902: [com- rent] - get 22 Pcasses
2025-07-20 13:31:54,044: Pcases not found. status code: 200.
2025-07-20 13:31:54,121: [resland- buy] - get 22 Pcasses
2025-07-20 13:31:54,200: Pcases not found. status code: 200.
2025-07-20 13:31:54,201: Pcases not founded after retrys.
2025-07-20 13:31:54,201: update('res','buy') is done
2025-07-20 13:31:54,901: Message: session not created: This version of ChromeDriver only supports Chrome version 136
Current browser version is 138.0.7204.157 with binary path /opt/google/chrome/chrome
Stacktrace:
#0 0x604154f5771a <unknown>
#1 0x6041549fa0a0 <unknown>
#2 0x604154a3aa47 <unknown>
#3 0x604154a39935 <unknown>
#4 0x604154a3498c <unknown>
#5 0x604154a2fc0f <unknown>
#6 0x604154a7fd75 <unknown>
#7 0x604154a7f296 <unknown>
#8 0x604154a71173 <unknown>
#9 0x604154a3dd4b <unknown>
#10 0x604154a3e9b1 <unknown>
#11 0x604154f1c8cb <unknown>
#12 0x604154f207ca <unknown>
#13 0x604154f04622 <unknown>
#14 0x604154f21354 <unknown>
#15 0x604154ee945f <unknown>
#16 0x604154f454f8 <unknown>
#17 0x604154f456d6 <unknown>
#18 0x604154f56586 <unknown>
#19 0x7067bc2a1e2e <unknown>
#20 0x7067bc333a4c <unknown>
https://divar.ir/v/%D8%A2%D9%BE%D8%A7%D8%B1%D8%AA%D9%85%D8%A7%D9%86-%DB%B6%DB%B8%D9%85%D8%AA%D8%B1%DB%8C-%D8%AF%D8%B1-%D8%B4%D9%87%D8%B1%DA%A9-%D9%88%D9%84%DB%8C%D8%B9%D8%B5%D8%B1/AawReTk_
2025-07-20 13:31:54,901: ----
2025-07-20 13:31:54,922: Message: session not created: This version of ChromeDriver only supports Chrome version 136
Current browser version is 138.0.7204.157 with binary path /opt/google/chrome/chrome
Stacktrace:
#0 0x6162b5c2071a <unknown>
#1 0x6162b56c30a0 <unknown>
#2 0x6162b5703a47 <unknown>
#3 0x6162b5702935 <unknown>
#4 0x6162b56fd98c <unknown>
#5 0x6162b56f8c0f <unknown>
#6 0x6162b5748d75 <unknown>
#7 0x6162b5748296 <unknown>
#8 0x6162b573a173 <unknown>
#9 0x6162b5706d4b <unknown>
#10 0x6162b57079b1 <unknown>
#11 0x6162b5be58cb <unknown>
#12 0x6162b5be97ca <unknown>
#13 0x6162b5bcd622 <unknown>
#14 0x6162b5bea354 <unknown>
#15 0x6162b5bb245f <unknown>
#16 0x6162b5c0e4f8 <unknown>
#17 0x6162b5c0e6d6 <unknown>
#18 0x6162b5c1f586 <unknown>
#19 0x7ce2c94a1e2e <unknown>
#20 0x7ce2c9533a4c <unknown>
https://divar.ir/v/%D9%85%D8%B3%D8%AA%D8%BA%D9%84%D8%A7%D8%AA-%D8%AF%D8%B1%D8%A8%D8%B3%D8%AA-%D9%85%D9%88%D9%82%D8%B9%DB%8C%D8%AA-%D8%A7%D8%AF%D8%A7%D8%B1%DB%8C/AaT5JcYd
2025-07-20 13:31:54,922: ----
2025-07-20 13:31:54,923: Message: session not created: This version of ChromeDriver only supports Chrome version 136
Current browser version is 138.0.7204.157 with binary path /opt/google/chrome/chrome
Stacktrace:
#0 0x5b47f13c171a <unknown>
#1 0x5b47f0e640a0 <unknown>
#2 0x5b47f0ea4a47 <unknown>
#3 0x5b47f0ea3935 <unknown>
#4 0x5b47f0e9e98c <unknown>
#5 0x5b47f0e99c0f <unknown>
#6 0x5b47f0ee9d75 <unknown>
#7 0x5b47f0ee9296 <unknown>
#8 0x5b47f0edb173 <unknown>
#9 0x5b47f0ea7d4b <unknown>
#10 0x5b47f0ea89b1 <unknown>
#11 0x5b47f13868cb <unknown>
#12 0x5b47f138a7ca <unknown>
#13 0x5b47f136e622 <unknown>
#14 0x5b47f138b354 <unknown>
#15 0x5b47f135345f <unknown>
#16 0x5b47f13af4f8 <unknown>
#17 0x5b47f13af6d6 <unknown>
#18 0x5b47f13c0586 <unknown>
#19 0x70ec126a1e2e <unknown>
#20 0x70ec12733a4c <unknown>
https://divar.ir/v/%D9%81%D8%B1%D9%88%D8%B4-%D8%B2%D9%85%DB%8C%D9%86-%DB%B3%DB%B0%DB%B0-%D9%85%D8%AA%D8%B1%DB%8C-%D8%B3%D9%86%D8%AF-%D8%AA%DA%A9-%D8%A8%D8%B1%DA%AF/Aa7NmXYn
2025-07-20 13:31:54,923: ----
2025-07-20 13:31:55,060: Pcases not found. status code: 200.
2025-07-20 13:31:55,187: Pcases not found. status code: 200.
2025-07-20 13:31:55,270: Pcases not found. status code: 200.
2025-07-20 13:31:55,270: Pcases not founded after retrys.
2025-07-20 13:31:55,270: update('com','buy') is done
2025-07-20 13:32:02,480: stop func is calling...
2025-07-20 13:32:02,943: stop func is calling...
2025-07-20 13:32:03,176: stop func is calling...
2025-07-20 13:32:03,410: stop func is calling...
